---
 
- name: gerando senha aleatoria
  delegate_to: localhost
  ansible.builtin.shell: newpass -l 25
  register: mynewpass
    
## imprimir em tela as senhas geradas ## 
#- name: debug
  #debug:
    #var: mynewpass.stdout 

- name: salvando senha gerada em um arquivo
  lineinfile:
     line: "Hostname: {{ ansible_hostname }} IP: {{ ansible_default_ipv4.address }} Senha: {{ mynewpass.stdout }}"
     insertafter: EOF
     dest: $HOME/senhas/saida3.log
  delegate_to: localhost

- name: alterando a senha do usuario
  ansible.builtin.user:
    name: "{{ name_user }}"
    password: "{{ mynewpass.stdout | password_hash('sha512') }}"
  become: true

...
